### ISSUE TITLE
String.includes() not supported in IE

### ISSUE THREAD

**Issue by tedw** [swup/body-class-plugin#1]
IE11 lacks support for [`String.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) ([browser support](https://caniuse.com/#feat=es6-string-includes)).

Can we change this code to use `indexOf()` instead?
https://github.com/swup/body-class-plugin/blob/05535e88b9a52661763fd4677c6474a09774555f/src/index.js#L41-L43

At the very least, would be good to mention browser support in the docs and link to polyfills.

Thanks!

**Comment by gmrchk** [comment]
I think it would be helpful to keep these "modern" functions in swup source code.
I will look into some options on updating babel transpiling stuff (it needs an update anyway).   

Thank you for reporting!

**Comment by gmrchk** [comment]
I can't get to the babel updates. Went with your proposed fix 👍
