### ISSUE TITLE
How to use exactly?

### ISSUE THREAD

**Issue by bigskillet** [swup/body-class-plugin#2]
I have the plugin installed and can see it pinging the <body> tag in Chrome Dev Tools, but it's not changing, adding, removing any classes. How exactly do I add a class based on the current page? Is there some more javascript that needs to be added besides what's shown in the example?

**Comment by gmrchk** [comment]
Hey, sorry for the delay.
The plugin automatically detects any classes of the next page on the `body` tag and replaces them. No special steps are needed, only adding the classes on `body` in the page source.
