### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by jorisnoo** [swup/body-class-plugin#27]
**Description of the issue**

It appears that the plugin is not working as expected in Safari (classes are not removed/added on navigation) while Firefox has no issues.

**Context and environment**

I tested on Safari 16.6, 17.0 and iOS 16.6.
In case this is not easily reproducible, I'll gladly create a demo.

Thank you very much for your support!

**Before creating this issue...**

- [x] Have you provided all helpful information available?
- [x] Have you checked closed issues for similar/related problems?
- [ ] Have you considered creating a demo so we can help you better?

**Comment by daun** [comment]
I can't reproduce this one here, at least not on Safari 16.5. Could you create a demo, please? Could this be another plugin interfering?

**Comment by jorisnoo** [comment]
Ah, sorry — Yes, disabling the Preload Plugin solves this. May be related to the issue with `requestIdleCallback`.
