### ISSUE TITLE
Update data attributes on `body` element

### ISSUE THREAD

**Issue by daun** [swup/body-class-plugin#36]
### Describe the problem 🧐

Currently, only the classname is updated. Data attributes are left alone.

### Describe the propsed solution 😎

Allow configuring which attributes get updated: `data-*`, `lang`, etc.

### Alternatives considered 🤔

Hooks in every project.

### How important is this feature to you? 🧭

Would make my life a lot easier

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
Same as in head plugin. I'd also vote for a configurable list with a default of lang and dir.

**Comment by giorgiodare** [comment]
+1

**Comment by daun** [comment]
Released in v3.3.0
