### ISSUE TITLE
Getting "TypeError: Cannot read property 'pageClass' of undefined" when using plugin

### ISSUE THREAD

**Issue by alirexa** [swup/body-class-plugin#8]
**Describe your issue**:
I'm trying to use this plugin in my wordpress theme, the SWUP works* but it doesn't work and returns this error:
```
TypeError: Cannot read property 'pageClass' of undefined
    at vendor.min.js?ver=20151215:1
    at vendor.min.js?ver=20151215:1
    at Array.forEach (<anonymous>)
    at w.e.default [as triggerEvent] (vendor.min.js?ver=20151215:1)
    at w.e.default [as renderPage] (vendor.min.js?ver=20151215:1)
    at vendor.min.js?ver=20151215:1
```
*I have a problem with the SWUP too which I commented [here](https://github.com/swup/swup/issues/19#issuecomment-724647240)

**Swup config or any additional relevant code used**:

```javascript
const domain = window.location.origin
const options = {    
    linkSelector: `a[href*="${domain}"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]), a[xlink\\:href]`,
    containers: [".site"],
    plugins: [new SwupBodyClassPlugin()]
};
const swup = new Swup(options);
```
I also tried the config without the linkSelector change and other linkSelector configs but I still get this error.

**Before creating this issue, did you think of...**:
- [-] Have you checked closed issues for similar/related problems.
- [-] Have you provided all helpful information available? 
- [-] Have you considered creating a demo so we can help you better?

Edit:
I explained the fix [here](https://github.com/swup/body-class-plugin/issues/8#issuecomment-728946836)

**Comment by franboud** [comment]
Hi alirexa,

I have the same problem, but only if I call a page using the loadPage() function. Standard links works well. Is your problem the same as mine?

**Comment by alirexa** [comment]
Hey @franboud 

No, my problem was actually something else, I'm using Babel ( [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) )in that project for backward compatibility to ES5 JS and it was causing this problem. I excluded that body-class from processing through Babel and it got fixed.

**Comment by franboud** [comment]
Thanks for letting me know @alirexa

**Comment by gmrchk** [comment]
I take it this is resolved. 👍  @franboud if you still have problems, please create an issue describing it.
